name: wsi-mil
channels:
    - conda-forge
dependencies:
    - pytorch
    - pytorch-lightning
    - torchvision
    - pandas
    - openslide
    - ray-core
    - matplotlib
    - numpy
    - omegaconf
    - scikit-learn
    - pillow
    - onnxruntime
    - rich
    - tiatoolbox
    - scipy
    - scikit-image
    - tqdm
    - fastai
    - pip
    - pip:
        - aim
        - git+https://github.com/oval-group/smooth-topk@12c1645f187e2fa0c05f47bf1fe48864d4bd2707
        - nystrom_attention
        - pytorch_toolbelt

